server:
  port: 8083
  servlet:
    context-path: /redis


spring:
  # redis配置
  redis:
    # 填写Redis IP 号
    host: 127.0.0.1
    # 填写Redis 端口号
    port: 6379
    # 填写Redis 密码
    password: 123456
    jedis:
      pool:
        max-active: 300
        max-wait: 30000
        max-idle: 10
        min-idle: 10
    timeout: 10000
    #指定redis存储库
    database: 2
    #连接池内空闲连接至少保留毫秒数
    minEvictableIdleTimeMillis: 300000
    #连接空闲时, 间隔秒数自动检查连接可用性,redis断开可用来自恢复连接
    timeBetweenEvictionRunsMillis: 60000
